server:
  port: 9000
  context-path: /api

spring:
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy
    deserialization.fail-on-unknown-properties: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
  session:
    key: BOARD_SESSION_KEY

security:
  oauth2:
    client:
      clientId: 152190478688056
      clientSecret: d3f930dbe45138517f9358bd25eec13e
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

---

spring:
  profiles: local
  datasource:
    username: test
    password: test
    url: jdbc:mysql://localhost/exquizme?useUnicode=true&characterEncoding=utf8&useSSL=false

server:
  host: http://localhost:9000
